language: c
compiler: gcc
dist: xenial
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
before_script:
- pip install --user redis ramp-packer rmtest
- git clone -b 4.0.1 --depth 1 https://github.com/antirez/redis.git
- cd redis
- make
- cd ..
env:
- REDIS_MODULE_PATH=$TRAVIS_BUILD_DIR/src/libmodule.so REDIS_PATH=$TRAVIS_BUILD_DIR/redis/src/redis-server
script:
- cmake --version
- cmake .
- make module
# - make test